version: "3.7"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - door
  app:
    image: jchorl/door
    privileged: true
    ports:
      - "8000:8000"
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    environment:
        FLASK_ENV: "production"
    volumes:
      - type: bind
        source: /sys
        target: /sys
    networks:
      - door
    depends_on:
      - redis
      - celeryworker
  celeryworker:
    image: jchorl/door
    privileged: true
    command: ["celery", "worker", "-A", "door.celery", "--loglevel=info"]
    volumes:
      - type: bind
        source: /sys
        target: /sys
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    networks:
      - door
    depends_on:
      - redis

networks:
  door:
