version: "3.7"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - door
  app:
    image: python:3.8
    command: ["sh", "-c", "pip install -r requirements.txt && python3 door.py"]
    ports:
      - "8000:8000"
    environment:
        FLASK_ENV: "production"
    networks:
      - door
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - redis
      - celeryworker
  celeryworker:
    image: python:3.8
    command: ["sh", "-c", "pip install -r requirements.txt && celery worker -A door.celery --loglevel=info"]
    networks:
      - door
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - redis

networks:
  door:
