version: "3.7"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - door
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  app:
    image: python:3.8
    command: ["sh", "-c", "pip install -r requirements.txt && python3 hi.py"]
    ports:
      - "8000:8000"
    networks:
      - door
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  door:
