version: "3.7"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - door
  app:
    image: jchorl/door
    ports:
      - "8000:8000"
    environment:
        FLASK_ENV: "development"
    networks:
      - door
    depends_on:
      - redis
      - celeryworker
  celeryworker:
    image: jchorl/door
    command: ["celery", "worker", "-A", "door.celery", "--loglevel=info"]
    networks:
      - door
    depends_on:
      - redis

networks:
  door:
